#### Importing Libraries

In [2]:
import numpy as np
#numpy aliased as np

import pandas as pd
#pandas aliased as pd

import matplotlib.pyplot as plt
#matplotlib.pyplot aliased as plt

import seaborn as sns
#seaborn aliased as sns

import pickle
#pickle for saving model and objects

#importing warning module for ignoring warning messages
import warnings
warnings.filterwarnings('ignore')

#### Loading Data using pandas library

In [3]:
#loading data using pandas library
df_train = pd.read_csv("counterfeit_train.csv")

#Showing Top 5 rows
df_train.head()

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales
0,RRA15,13.100,Area046,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,1775.5026
1,YVV26,NaN,Area027,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520
2,LJC15,9.025,Area046,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,2603.0920
3,GWC40,11.800,Area046,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,1101.7130
4,QMN13,NaN,Area019,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402

In [4]:
df_train.shape

(6818, 12)

In [5]:
#loading data using pandas library
df_test = pd.read_csv("counterfeit_test.csv")

#Showing Top 5 rows
df_test.head()

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level
0,HLZ81,NaN,Area027,1983,85.5328,Antibiotics,mild,0.112747,CityLimits,Tier 3,Medium
1,ECE94,13.45,Area045,2000,257.1460,OralContraceptives,mild,0.144446,DownTown,Tier 2,Unknown
2,SAD14,7.10,Area045,2000,98.1172,Antipyretics,mild,0.144221,DownTown,Tier 2,Unknown
3,EQV63,18.30,Area010,1996,135.3730,Tranquilizers,mild,0.100388,MidTownResidential,Tier 3,Unknown
4,AIR10,NaN,Area019,1983,112.8016,OralContraceptives,mild,0.022585,MidTownResidential,Tier 1,Small

In [6]:
df_test.shape

(1705, 11)

#### Checking data types of Columns

In [7]:
#Checking data types of columns in dataframe
df_train.dtypes

Medicine_ID             object
Counterfeit_Weight     float64
DistArea_ID             object
Active_Since             int64
Medicine_MRP           float64
Medicine_Type           object
SidEffect_Level         object
Availability_rating    float64
Area_Type               object
Area_City_Type          object
Area_dist_level         object
Counterfeit_Sales      float64
dtype: object

In [8]:
#Checking data types of columns in dataframe
df_test.dtypes

Medicine_ID             object
Counterfeit_Weight     float64
DistArea_ID             object
Active_Since             int64
Medicine_MRP           float64
Medicine_Type           object
SidEffect_Level         object
Availability_rating    float64
Area_Type               object
Area_City_Type          object
Area_dist_level         object
dtype: object

In [9]:
#Checking null values of columns in dataframe
df_train.isnull().sum()

Medicine_ID               0
Counterfeit_Weight     1166
DistArea_ID               0
Active_Since              0
Medicine_MRP              0
Medicine_Type             0
SidEffect_Level           0
Availability_rating       0
Area_Type                 0
Area_City_Type            0
Area_dist_level           0
Counterfeit_Sales         0
dtype: int64

In [10]:
#Checking null values of columns in dataframe
df_test.isnull().sum()

Medicine_ID              0
Counterfeit_Weight     297
DistArea_ID              0
Active_Since             0
Medicine_MRP             0
Medicine_Type            0
SidEffect_Level          0
Availability_rating      0
Area_Type                0
Area_City_Type           0
Area_dist_level          0
dtype: int64

In [11]:
#Checking counts in each columns
df_train.count()

Medicine_ID            6818
Counterfeit_Weight     5652
DistArea_ID            6818
Active_Since           6818
Medicine_MRP           6818
Medicine_Type          6818
SidEffect_Level        6818
Availability_rating    6818
Area_Type              6818
Area_City_Type         6818
Area_dist_level        6818
Counterfeit_Sales      6818
dtype: int64

In [12]:
#Checking counts in each columns
df_test.count()

Medicine_ID            1705
Counterfeit_Weight     1408
DistArea_ID            1705
Active_Since           1705
Medicine_MRP           1705
Medicine_Type          1705
SidEffect_Level        1705
Availability_rating    1705
Area_Type              1705
Area_City_Type         1705
Area_dist_level        1705
dtype: int64

In [13]:
#Checking Descriptive Statistical Details
df_train.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Medicine_ID,6818,1557,RQS74,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Counterfeit_Weight,5652.0,NaN,NaN,NaN,14.115057,4.649668,5.855,9.995,13.8,18.05,22.65
DistArea_ID,6818,10,Area017,760,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active_Since,6818.0,NaN,NaN,NaN,1995.836316,8.368979,1983.0,1985.0,1997.0,2002.0,2007.0
Medicine_MRP,6818.0,NaN,NaN,NaN,151.401518,62.203961,41.79,104.5094,153.1957,196.14835,277.1884
Medicine_Type,6818,16,Hreplacements,976,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SidEffect_Level,6818,2,mild,4434,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Availability_rating,6818.0,NaN,NaN,NaN,0.079174,0.051481,0.013,0.040058,0.066955,0.107697,0.341391
Area_Type,6818,4,DownTown,4481,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area_City_Type,6818,3,Tier 3,2655,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area_dist_level,6818,4,Medium,2203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Counterfeit_Sales,6818.0,NaN,NaN,NaN,2280.58348,1693.354404,146.29,933.2656,1902.6704,3207.6384,13199.9648

In [14]:
#Checking Descriptive Statistical Details
df_test.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Medicine_ID,1705,1049,BTP27,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Counterfeit_Weight,1408.0,NaN,NaN,NaN,14.328604,4.616129,5.855,10.3,14.3,18.3,22.65
DistArea_ID,1705,10,Area027,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active_Since,1705.0,NaN,NaN,NaN,1995.814076,8.38531,1983.0,1985.0,1997.0,2002.0,2007.0
Medicine_MRP,1705.0,NaN,NaN,NaN,150.857964,62.575018,41.59,102.8804,153.7154,195.3898,277.1884
Medicine_Type,1705,16,Antibiotics,262,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SidEffect_Level,1705,2,mild,1083,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Availability_rating,1705.0,NaN,NaN,NaN,0.078963,0.052076,0.013,0.039831,0.066693,0.10722,0.32409
Area_Type,1705,4,DownTown,1096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area_City_Type,1705,3,Tier 3,695,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area_dist_level,1705,4,Medium,590,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#Checking null values and datatypes
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6818 entries, 0 to 6817
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Medicine_ID          6818 non-null   object
 1   Counterfeit_Weight   5652 non-null   float64
 2   DistArea_ID          6818 non-null   object
 3   Active_Since         6818 non-null   int64
 4   Medicine_MRP         6818 non-null   float64
 5   Medicine_Type        6818 non-null   object
 6   SidEffect_Level      6818 non-null   object
 7   Availability_rating  6818 non-null   float64
 8   Area_Type            6818 non-null   object
 9   Area_City_Type       6818 non-null   object
 10  Area_dist_level      6818 non-null   object
 11  Counterfeit_Sales    6818 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 639.3+ KB

In [16]:
#Checking null values and datatypes
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Medicine_ID          1705 non-null   object
 1   Counterfeit_Weight   1408 non-null   float64
 2   DistArea_ID          1705 non-null   object
 3   Active_Since         1705 non-null   int64
 4   Medicine_MRP         1705 non-null   float64
 5   Medicine_Type        1705 non-null   object
 6   SidEffect_Level      1705 non-null   object
 7   Availability_rating  1705 non-null   float64
 8   Area_Type            1705 non-null   object
 9   Area_City_Type       1705 non-null   object
 10  Area_dist_level      1705 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 146.7+ KB

In [17]:
for i in df_train.select_dtypes(include = ['object']):
    print('No. of Unique values in column',i,'is:',df_train[i].nunique())
    print('\n')
    print(df_train[i].unique())
    print('\n')
    print('*-'*50,'\n')

No. of Unique values in column Medicine_ID is: 1557


['RRA15' 'YVV26' 'LJC15' ... 'KGC13' 'JTW13' 'OPM10']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column DistArea_ID is: 10


['Area046' 'Area027' 'Area019' 'Area045' 'Area018' 'Area013' 'Area017'
 'Area010' 'Area035' 'Area049']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Medicine_Type is: 16


['Antimalarial' 'Mstablizers' 'Cardiac' 'OralContraceptives'
 'Hreplacements' 'Antiseptics' 'Statins' 'Analgesics' 'MuscleRelaxants'
 'Antibiotics' 'Antifungal' 'Antiviral' 'Tranquilizers' 'Antacids'
 'Antipyretics' 'Stimulants']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column SidEffect_Level is: 2


['critical' 'mild']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Area_Type is: 4


['DownTown' 'CityLimits' 'MidTownResidential' 'Industrial']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Area_City_Type is: 3


['Tier 1' 'Tier 3' 'Tier 2']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Area_dist_level is: 4


['Small' 'Medium' 'Unknown' 'High']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

In [18]:
for i in df_test.select_dtypes(include = ['object']):
    print('No. of Unique values in column',i,'is:',df_test[i].nunique())
    print('\n')
    print(df_test[i].unique())
    print('\n')
    print('*-'*50,'\n')

No. of Unique values in column Medicine_ID is: 1049


['HLZ81' 'ECE94' 'SAD14' ... 'RTV34' 'KXW10' 'NDL93']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column DistArea_ID is: 10


['Area027' 'Area045' 'Area010' 'Area019' 'Area046' 'Area017' 'Area018'
 'Area013' 'Area049' 'Area035']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Medicine_Type is: 16


['Antibiotics' 'OralContraceptives' 'Antipyretics' 'Tranquilizers'
 'Antacids' 'Cardiac' 'Hreplacements' 'Mstablizers' 'Antiseptics'
 'Antifungal' 'MuscleRelaxants' 'Analgesics' 'Statins' 'Antimalarial'
 'Stimulants' 'Antiviral']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column SidEffect_Level is: 2


['mild' 'critical']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Area_Type is: 4


['CityLimits' 'DownTown' 'MidTownResidential' 'Industrial']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Area_City_Type is: 3


['Tier 3' 'Tier 2' 'Tier 1']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

No. of Unique values in column Area_dist_level is: 4


['Medium' 'Unknown' 'Small' 'High']


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

In [19]:
#Checking Duplicates entry
df_train.duplicated().sum()

0

In [20]:
#Checking Duplicates entry
df_test.duplicated().sum()

0

In [21]:
df1 = df_train.copy()
df1.drop(['Medicine_ID','Counterfeit_Weight'], inplace = True, axis=1)

In [22]:
df1.head()

,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales
0,Area046,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,1775.5026
1,Area027,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520
2,Area046,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,2603.0920
3,Area046,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,1101.7130
4,Area019,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402

In [23]:
df1.shape

(6818, 10)

In [24]:
df1.describe().round().T

,count,mean,std,min,25%,50%,75%,max
Active_Since,6818.0,1996.0,8.0,1983.0,1985.0,1997.0,2002.0,2007.0
Medicine_MRP,6818.0,151.0,62.0,42.0,105.0,153.0,196.0,277.0
Availability_rating,6818.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Counterfeit_Sales,6818.0,2281.0,1693.0,146.0,933.0,1903.0,3208.0,13200.0

In [25]:
df1.head()

,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales
0,Area046,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,1775.5026
1,Area027,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520
2,Area046,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,2603.0920
3,Area046,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,1101.7130
4,Area019,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402

In [26]:
x_test = df_test.copy()
x_test.drop(['Medicine_ID','Counterfeit_Weight'], inplace = True, axis=1)
x_test.head()

,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level
0,Area027,1983,85.5328,Antibiotics,mild,0.112747,CityLimits,Tier 3,Medium
1,Area045,2000,257.1460,OralContraceptives,mild,0.144446,DownTown,Tier 2,Unknown
2,Area045,2000,98.1172,Antipyretics,mild,0.144221,DownTown,Tier 2,Unknown
3,Area010,1996,135.3730,Tranquilizers,mild,0.100388,MidTownResidential,Tier 3,Unknown
4,Area019,1983,112.8016,OralContraceptives,mild,0.022585,MidTownResidential,Tier 1,Small

In [27]:
for col in df1.select_dtypes(include = 'object'): #['Medicine_Type','SidEffect_Level','Area_Type','Area_City_Type','Area_dist_level',"DistArea_ID"] 
    temp=pd.get_dummies(df1[col],prefix=col,drop_first=True,dtype = 'float')#drop_first=True
    df1=pd.concat([temp,df1],axis=1)
    df1.drop([col],axis = 1,inplace=True)
  
    temp=pd.get_dummies(x_test[col],prefix=col,drop_first=True,dtype = 'float')#drop_first=True
    x_test=pd.concat([temp,x_test],axis=1)
    x_test.drop([col],axis =1,inplace=True)

In [28]:
df1.columns

Index(['Area_dist_level_Medium', 'Area_dist_level_Small',
       'Area_dist_level_Unknown', 'Area_City_Type_Tier 2',
       'Area_City_Type_Tier 3', 'Area_Type_DownTown', 'Area_Type_Industrial',
       'Area_Type_MidTownResidential', 'SidEffect_Level_mild',
       'Medicine_Type_Antacids', 'Medicine_Type_Antibiotics',
       'Medicine_Type_Antifungal', 'Medicine_Type_Antimalarial',
       'Medicine_Type_Antipyretics', 'Medicine_Type_Antiseptics',
       'Medicine_Type_Antiviral', 'Medicine_Type_Cardiac',
       'Medicine_Type_Hreplacements', 'Medicine_Type_Mstablizers',
       'Medicine_Type_MuscleRelaxants', 'Medicine_Type_OralContraceptives',
       'Medicine_Type_Statins', 'Medicine_Type_Stimulants',
       'Medicine_Type_Tranquilizers', 'DistArea_ID_Area013',
       'DistArea_ID_Area017', 'DistArea_ID_Area018', 'DistArea_ID_Area019',
       'DistArea_ID_Area027', 'DistArea_ID_Area035', 'DistArea_ID_Area045',
       'DistArea_ID_Area046', 'DistArea_ID_Area049', 'Active_Since',
       'Medicine_MRP', 'Availability_rating', 'Counterfeit_Sales'],
      dtype='object')

In [29]:
x_test.columns

Index(['Area_dist_level_Medium', 'Area_dist_level_Small',
       'Area_dist_level_Unknown', 'Area_City_Type_Tier 2',
       'Area_City_Type_Tier 3', 'Area_Type_DownTown', 'Area_Type_Industrial',
       'Area_Type_MidTownResidential', 'SidEffect_Level_mild',
       'Medicine_Type_Antacids', 'Medicine_Type_Antibiotics',
       'Medicine_Type_Antifungal', 'Medicine_Type_Antimalarial',
       'Medicine_Type_Antipyretics', 'Medicine_Type_Antiseptics',
       'Medicine_Type_Antiviral', 'Medicine_Type_Cardiac',
       'Medicine_Type_Hreplacements', 'Medicine_Type_Mstablizers',
       'Medicine_Type_MuscleRelaxants', 'Medicine_Type_OralContraceptives',
       'Medicine_Type_Statins', 'Medicine_Type_Stimulants',
       'Medicine_Type_Tranquilizers', 'DistArea_ID_Area013',
       'DistArea_ID_Area017', 'DistArea_ID_Area018', 'DistArea_ID_Area019',
       'DistArea_ID_Area027', 'DistArea_ID_Area035', 'DistArea_ID_Area045',
       'DistArea_ID_Area046', 'DistArea_ID_Area049', 'Active_Since',
       'Medicine_MRP', 'Availability_rating'],
      dtype='object')

In [30]:
x_test.head()

,Area_dist_level_Medium,Area_dist_level_Small,Area_dist_level_Unknown,Area_City_Type_Tier 2,Area_City_Type_Tier 3,Area_Type_DownTown,Area_Type_Industrial,Area_Type_MidTownResidential,SidEffect_Level_mild,Medicine_Type_Antacids,...,DistArea_ID_Area018,DistArea_ID_Area019,DistArea_ID_Area027,DistArea_ID_Area035,DistArea_ID_Area045,DistArea_ID_Area046,DistArea_ID_Area049,Active_Since,Medicine_MRP,Availability_rating
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1983,85.5328,0.112747
1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2000,257.1460,0.144446
2,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2000,98.1172,0.144221
3,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996,135.3730,0.100388
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1983,112.8016,0.022585

In [31]:
df1.shape

(6818, 37)

#### Select the Dependent and Independent Features

In [32]:
target='Counterfeit_Sales'

In [33]:
x=df1.drop(target,axis = 1)
y=df1[target]

In [34]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [35]:
d = {'Model':[],'MAE':[],'MSE':[],'RMSE':[],'R2_SCORE':[],'Train_Score':[],'Test_Score':[],'Score':[]}

def eval_model(model,model_name,x_train,y_train,x_test,y_test,y_pred):
    mae = mean_absolute_error(y_test,y_pred)
    mse = mean_squared_error(y_test,y_pred)
    rmse =np.sqrt(mean_squared_error(y_test,y_pred))
    r2s = r2_score(y_test, y_pred)
    Train_Score = model.score(x_train, y_train)
    Test_Score = model.score(x_test, y_test)
    Mae_Score = (1-(mae/1660))
    print('MAE:', mae)
    print('MSE:', mse)
    print('RMSE:', rmse)
    print('R2_Score:', r2s)
    print('Training Score',model.score(x_train,y_train))  # Training dataset Accuracy
    print('Testing Score',model.score(x_test,y_test))     # Testing dataset accuracy
    print('MAE_Score:', Mae_Score)
    d['Model'].append(model_name)
    d['MAE'].append(mae)
    d['MSE'].append(mse)
    d['RMSE'].append(rmse)
    d['R2_SCORE'].append(r2s)
    d['Train_Score'].append(Train_Score)
    d['Test_Score'].append(Test_Score)
    d['Score'].append(Mae_Score)
    

    
def mscore(model):
    print('Training Score',model.score(x_train,y_train))  # Training dataset Accuracy
    print('Testing Score',model.score(x_test,y_test))     # Testing dataset accuracy

In [36]:
def reg_eval_metrics(y_test, y_pred):
    mae = mean_absolute_error(y_test,y_pred)
    mse = mean_squared_error(y_test,y_pred)
    rmse =np.sqrt(mean_squared_error(y_test,y_pred))
    r2s = r2_score(y_test, y_pred)
    print('MAE:', mae)
    print('MSE:', mse)
    print('RMSE:', rmse)
    print('R2_Score:', r2s)

def train_test_score(model):
    print('Training_Score:', model.score(x_train, y_train))
    print('Testing_Score:', model.score(x_test, y_test))

In [37]:
from sklearn.model_selection import GridSearchCV

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
# Define the hyperparameter grid
param_grid = {
    'fit_intercept': [True, False]
    # 'alpha': np.linspace(0,50,200),
    # Add other hyperparameters and their possible values
}

# Create an instance of your model
model = LinearRegression()

# Perform grid search with cross-validation
grid_search = GridSearchCV(model, param_grid =  param_grid, cv=5, scoring='neg_mean_absolute_error')
grid_search.fit(x, y)

# Get the best hyperparameters and best score
best_params1 = grid_search.best_params_
print(best_params1)
best_mae1 = grid_search.best_score_
print(best_mae1)

# Train a new instance of the model with the best hyperparameters
# best_model = YourModel(**best_params)
# best_model.fit(X_train, y_train)

{'fit_intercept': True}
-828.9553444819867

In [40]:
from sklearn.neighbors import KNeighborsRegressor

In [41]:
# Define the parameter grid with loops for specific increments
param_grid = {
    'n_neighbors' : np.arange(1,100)
}

# Create the RandomForestRegressor
estimator = KNeighborsRegressor()

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator= estimator, param_grid=param_grid, scoring='neg_mean_absolute_error', cv=10)

# Fit the grid search to the data
grid_search.fit(x, y)

# Get the best parameters and modelc
best_params2 = grid_search.best_params_
print(best_params2)
# best_model = grid_search.best_estimator_
# print(best_model)
best_mae2 = grid_search.best_score_
print(best_mae2)

{'n_neighbors': 6}
-824.0848083347113

In [42]:
from sklearn.linear_model import Ridge, Lasso

In [43]:
from sklearn.model_selection import GridSearchCV

# Create instances of estimator models
ridge = Ridge()
lasso = Lasso()

# Create the RandomForestRegressor
estimator = ridge

# Define the parameter grid with loops for specific increments
param_grid = {
    # 'ridge': {'alpha': np.linspace(0.01,100,1000)},
    'alpha': np.linspace(0.01,100,1000)
}


# Initialize GridSearchCV
grid_search = GridSearchCV(estimator= estimator, param_grid=param_grid,n_jobs = -1, verbose = 10 ,scoring='neg_mean_absolute_error', cv=10)

# Fit the grid search to the data
grid_search.fit(x, y)

# Get the best parameters and modelc
best_params = grid_search.best_params_
print(best_params)
best_model = grid_search.best_estimator_
print(best_model)
best_score = grid_search.best_score_
print(best_score)

Fitting 10 folds for each of 1000 candidates, totalling 10000 fits
{'alpha': 81.28315315315315}
Ridge(alpha=81.28315315315315)
-826.6825674338513

In [44]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid with loops for specific increments
param_grid = {
    'alpha' : np.linspace(0.01,100,1000)
}

# Create the RandomForestRegressor
estimator = Lasso()

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator= estimator, param_grid=param_grid, n_jobs = -1,verbose= 20,scoring='neg_mean_absolute_error', cv=10)#,neg_mean_squared_error

# Fit the grid search to the data
grid_search.fit(x, y)

# Get the best parameters and modelc
best_params = grid_search.best_params_
print(best_params)
# best_model = grid_search.best_estimator_
# print(best_model)
best_score = grid_search.best_score_
print(best_score)

Fitting 10 folds for each of 1000 candidates, totalling 10000 fits
{'alpha': 8.317477477477476}
-825.2989176722995

In [45]:
from sklearn.tree import DecisionTreeRegressor

In [46]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid with loops for specific increments
param_grid = {
    'max_depth': np.arange(1,40),
    'min_samples_split': np.arange(1,40)
}

# Create the RandomForestRegressor
estimator = DecisionTreeRegressor()

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator= estimator, param_grid=param_grid, n_jobs = -1,verbose= 20,scoring='neg_mean_absolute_error', cv=10)

# Fit the grid search to the data
grid_search.fit(x, y)

# Get the best parameters and modelc
best_params = grid_search.best_params_
print(best_params)
# best_model = grid_search.best_estimator_
# print(best_model)
best_score = grid_search.best_score_
print(best_score)

Fitting 10 folds for each of 1521 candidates, totalling 15210 fits
{'max_depth': 5, 'min_samples_split': 30}
-755.2707498435439

In [47]:
from sklearn.ensemble import RandomForestRegressor

In [59]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid with loops for specific increments
param_grid = {
    'n_estimators': [300],
    'max_depth': [6],
    'min_samples_split': [20]
}

# Create the RandomForestRegressor
estimator = RandomForestRegressor()

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator= estimator, param_grid=param_grid, n_jobs = -1,verbose= 20,scoring='neg_mean_absolute_error', cv=10)

# Fit the grid search to the data
grid_search.fit(x, y)

# Get the best parameters and model
best_params = grid_search.best_params_
print(best_params)
best_model = grid_search.best_estimator_
print(best_model)
best_score = grid_search.best_score_
print(best_score)

Fitting 10 folds for each of 1 candidates, totalling 10 fits
{'max_depth': 6, 'min_samples_split': 20, 'n_estimators': 300}
RandomForestRegressor(max_depth=6, min_samples_split=20, n_estimators=300)
-749.3848254945243

In [69]:
# m5 = RandomForestRegressor(n_estimators= 300,max_depth= 6,min_samples_split= 20,random_state= 42)#n_estimators= 125, max_depth= 5, min_samples_split= 14,
# m5.fit(x_train, y_train)
# y_pred5 = m5.predict(x_test)
# print(y_pred5)
# train_test_score(m5)
#Fitting 10 folds for each of 19 candidates, totalling 190 fits
# {'max_depth': 6, 'min_samples_split': 8, 'n_estimators': 300}
# RandomForestRegressor(max_depth=6, min_samples_split=8, n_estimators=300)
# -749.1477374640632

[ 258.14842539  969.45416409 3210.70567051 ... 3088.63987938  622.743726
 3026.12310437]
Training_Score: 0.6271684674263074
Testing_Score: 0.6128016343702976

In [60]:
print(x.shape)
print(y.shape)
print(x_test.shape)

(6818, 36)
(6818,)
(1705, 36)

In [61]:
ypred_test = grid_search.predict(x_test)
ypred_test

array([2288.52174492, 4053.9063971 , 1487.07429261, ..., 2963.93265465,
       3601.87765474, 3997.60265533])

In [62]:
df_test['Counterfiet_Sales'] = ypred_test
df_test.head()

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfiet_Sales
0,HLZ81,NaN,Area027,1983,85.5328,Antibiotics,mild,0.112747,CityLimits,Tier 3,Medium,2288.521745
1,ECE94,13.45,Area045,2000,257.1460,OralContraceptives,mild,0.144446,DownTown,Tier 2,Unknown,4053.906397
2,SAD14,7.10,Area045,2000,98.1172,Antipyretics,mild,0.144221,DownTown,Tier 2,Unknown,1487.074293
3,EQV63,18.30,Area010,1996,135.3730,Tranquilizers,mild,0.100388,MidTownResidential,Tier 3,Unknown,395.634153
4,AIR10,NaN,Area019,1983,112.8016,OralContraceptives,mild,0.022585,MidTownResidential,Tier 1,Small,352.723984

In [63]:
df_test.columns
df_test.shape

(1705, 12)

In [64]:
submission = df_test[['Medicine_ID','Counterfiet_Sales']]
submission.head()

  Medicine_ID  Counterfiet_Sales
0       HLZ81        2288.521745
1       ECE94        4053.906397
2       SAD14        1487.074293
3       EQV63         395.634153
4       AIR10         352.723984

In [65]:
submission.columns

Index(['Medicine_ID', 'Counterfiet_Sales'], dtype='object')

In [66]:
submission.to_csv('Sales.csv',index=False)